version: '3.8'

services:
  app:
    build: .
    container_name: bugnotify_app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=fastapi_db
      - COLLECTION_NAME=items
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - mongodb
      - redis
      - rabbitmq
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: bugnotify_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: bugnotify_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bugnotify_rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge